### ISSUE TITLE
Manifest file not generated

### ISSUE THREAD

**Issue by findela** [ooade/NextSimpleStarter#113]
![Screenshot from 2019-08-30 18-44-16](https://user-images.githubusercontent.com/8926058/64024881-04871400-cb59-11e9-9b55-e1f85a0711f8.png)
I tried exactly same installation that you provide in documentation, In my case the manifest file identity doesn't matches where your https://nextss.now.sh/ this one matches,can you little help what went wrong to solve this issue. I am using to host this on AWS to check, not on Now(Zeit). The install button on the address bar is not also showing in my case.

**Comment by ooade** [comment]
First off, you'd need to check if the service worker installs properly on your end. If not, you need to redirect `/static/service-worker.js` route to `/service-worker.js`.

**Comment by findela** [comment]
I figured out swDest: 'static/service-worker.js', in next config.js which will try to pick the file, but found this solutions registerSwPrefix: "/",it's not working!
