### ISSUE TITLE
Background Sync API support

### ISSUE THREAD

**Issue by rrjanbiah** [ooade/NextSimpleStarter#128]
Are there any support for Background Sync https://developers.google.com/web/tools/workbox/modules/workbox-background-sync and or a way to handle API calls in offline?

**Comment by ooade** [comment]
There's nothing stopping you from using Background Sync 🙂
Update your next.config.js to work with it and, you should be good to go.
For more info on what options to pass, [check this out](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin).
