### ISSUE TITLE
`Container` in `_app` has been deprecated and should be removed. 

### ISSUE THREAD

**Issue by mykolat** [ooade/NextSimpleStarter#132]
[ ready ] compiled successfully - ready on http://localhost:3000
Warning: the `Container` in `_app` has been deprecated and should be removed. https://err.sh/zeit/next.js/app-container-deprecated

Getting such error on start, how can I handle it?

**Comment by ooade** [comment]
Hi! Completely discard `Container` and, you're good to go. I'll update the repo today to fix that tho.

Thanks!

**Comment by ooade** [comment]
I've pushed it 🎉
