### ISSUE TITLE
Redux Dev Tools doesn't work

### ISSUE THREAD

**Issue by simonestic** [ooade/NextSimpleStarter#135]
Hey, thanks or this boilerplate, i think it'w awesome. but apparently redux devtools doesn't work.
any hint on that?

**Comment by ooade** [comment]
We don't use Redux. We're making use of React Hooks (useReducer) in place of redux. You could make use of React Dev Tools, tho, it doesn't offer as much flexibility as Redux Dev Tools. But, it should give as much context as possible.
