### ISSUE TITLE
Re-organize our README

### ISSUE THREAD

**Issue by ooade** [ooade/NextSimpleStarter#143]
We started this project not quite long after Next.js became public and we haven't really touched the README 😅

We've just been improving the code section and making it a lot better. I guess it's time to give the README a new structure, basically to pass the right message to new users.

Let's do this! 🚀

**Comment by rbhatt-pm** [comment]
```

```

**Comment by rbhatt-pm** [comment]
Dnx@

**Comment by rbhatt-pm** [comment]
> Dnx@

-

**Comment by Markkos89** [comment]
Hello, im trying to use this project as a template a project of mine and i cant do the deploy to Netlify. Would you be so kind to update the Readme.md file with proper instructions?

**Comment by ooade** [comment]
Hi @Markkos89!

We actually added a guide for Netlify [here](https://github.com/ooade/NextSimpleStarter#deploy-to-netlify). 

Cheers! 🎉

**Comment by ooade** [comment]
Fixed in #170
