### ISSUE TITLE
NextJS SW registration failed

### ISSUE THREAD

**Issue by seraj** [ooade/NextSimpleStarter#174]
hi
thanks for this awesome repo

I use this repo for my project and it's working fine.
but one thing happen for me.

I don't deploy it on now or Heroku. we have our server and I just use ssh for deploying the project on the server.

and this is my console

```
SW registration failed:  TypeError: Failed to register a ServiceWorker for scope ('https://dibaache.com/') with script ('https://dibaache.com/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.
```

**Comment by ooade** [comment]
The service worker is generated in the `_next/static` directory. It can be accessed via [this route](https://dibaache.com/_next/static/service-worker.js).

So, one thing you could do is set a redirect rule to help with that.

**Comment by seraj** [comment]
how can i do this?
i used this in `next.config.js` but it doesn't work
```
async redirects() {
	return [
	{
		source: "/_next/static/service-worker.js",
		destination: "/static/service-worker.js",
		permanent: true,
	},
	];
},
```

**Comment by ooade** [comment]
> UPDATE:
> i use `fs` package to copy `service-worker.js` to public folder and it's work.
> thank you
> 
> `copy-sw.js`:
> 
> ```
> const fs = require(`fs`).promises;
> 
> Promise.all(
> 	[`service-worker.js`].map((fileName) =>
> 		fs.copyFile(`./.next/static/${fileName}`, `./public/${fileName}`).then(() => fileName),
> 	),
> ).then((fileNames) =>
> 	console.log(`The following files were copied to './static': ${JSON.stringify(fileNames)}`),
> );
> ```
> 
> add this script to `package.json`
> 
> ```
> "copy-sw": "node copy-sw.js",
> "build": "next build && yarn copy-sw",
> ```

Cool. That works! Closing this issue as it's already resolved.
