### ISSUE TITLE
Redux-offline

### ISSUE THREAD

**Issue by sedubois** [ooade/NextSimpleStarter#23]
Hi! Thanks for this starter project, it's really helpful 👍 

Do you have any plans to add [redux-offline](https://github.com/jevakallio/redux-offline) to your example?

**Comment by ooade** [comment]
IMO, i feel its not necessary. I mean, data don't persist to a database/localstorage/.... As you can see [here](https://github.com/ooade/NextSimpleStarter/blob/master/actions/todo.js), we just have redux add/remove a todo and once we reload the page, off it goes :rocket:

But, we could still make this happen. If you interested, you can take it up and bump our version to 2.0.0.
I'd love to see comments from other people as well and thanks for raising this up :smile:

**Comment by sedubois** [comment]
Yeah don't know how big you want this to become but it would be really great to have a more realistic example 😄 Plugging a backend (I'd recommend [Graphcool](https://www.graph.cool/)) and a local storage (redux-offline using redux-persist under the hood) to have a more realistic example. I think it would be hugely helpful and very appreciated by @jevakallio and the guys from Zeit and Graphcool. Could definitely justify a little Medium article.

Don't know if I can make that contribution myself as my aim is to learn this stuff and have loads of other pieces to assemble in my project 😉 but if there's a PR coming I'm certainly willing to help reviewing.

**Comment by ooade** [comment]
Graphcool... I think we could have this on a different repo because i think it kinda goes against the "Simple Starter" name making it a lil bit verbose.

**Comment by sedubois** [comment]
Yes adding a backend makes things more complex of course, but as long as a backend is needed, I have the feeling that it's actually the easiest backend solution.

But I get it if you only wanted to demonstrate PWA here and not offline-first.

**Comment by ooade** [comment]
Yeah, you're right. Let's leave this open, as a reminder to work on it. I'll take this up if no one else will. Thanks :+1:

**Comment by vsc-github** [comment]
A very interesting project. I have one doubt though. Doesn't the PWA approach embraces offline-first architecture? If this project doesn't support offline first , what other PWA characteristics is it providing out of the box?

**Comment by ooade** [comment]
@vsc-github https://github.com/zeit/next.js/issues/861#issuecomment-296223233

**Comment by vsc-github** [comment]
@ooade Thanks, makes sense. I think addition of redux-offline would be a great addition to this project but then again it'll make this starter a very opinionated one. Ah, tough luck.

**Comment by sedubois** [comment]
Also, maintenance of Redux-offline seems to have stalled. Maybe need to look at technologies used inside hnpwa.com such as Workbox etc.

**Comment by ooade** [comment]
@sedubois Workbox is pretty hot :fire: :fire: Tried it's precaching mechanism via workbox-webpack-plugin, which doesn't yet support runtime caching. We can try adding it later with its other cool features like: 
- Background Sync
- Workbox Google Analytics
- and so on...
