### ISSUE TITLE
server.get is not function error

### ISSUE THREAD

**Issue by manishbalyan** [ooade/NextSimpleStarter#24]
I am using simple http server instead of express, but when i write this
    createServer.get('/sw.js', (req, res) => res.sendFile(path.resolve('./.next/sw.js')));
it through error that server.get is not a function
`const next = require('next')
const routes = require('./routes')
const app = next()
const handler = routes.getRequestHandler(app)

// Without express.js
const {createServer} = require('http')
    createServer.get('/sw.js', (req, res) => res.sendFile(path.resolve('./.next/sw.js')));
    createServer.get('*', (req, res) => handle(req, res));

app.prepare().then(() => {
  createServer(handler).listen(4000, err => {
    if (err) throw err
    console.log('> Ready on http://192.168.84.7:4000')
  })
})`

please help me out how to get sw.js file using simple http server

**Comment by ooade** [comment]
It feels like you don't want to use expressjs but this will lead to more and more errors coming your way while trying to set some things up. You can check out the [custom server example](https://github.com/zeit/next.js/blob/master/examples/custom-server/server.js) with nodejs or you can hack your way through it using http.request [here](https://nodejs.org/api/http.html#http_http_request_options_callback) 

Closing this issue as it does not inherently relate to this project. Thanks for stopping by :wink:
