### ISSUE TITLE
Question: .next/sw.js not static?

### ISSUE THREAD

**Issue by remy** [ooade/NextSimpleStarter#40]
I've just been reading through the service worker specific code in your repo, and I'm assuming there's a good reason for sw.js being in the .next directory - I just wondered if you could enlighten me? I'm looking at how I get a service worker in my own code base, but am seeing if it's possible to be done entirely from a statically generated directory.

Thanks in advance.

**Comment by ooade** [comment]
The Service Worker can also be generated on the static folder without any issue if served via a root path i.e. in the server.js file:
```js
app.serveStatic(req, res, path.resolve('./static/sw.js'))
``` 
It's just a matter of preference why i chose the .next directory :sweat_smile:

**Comment by ooade** [comment]
I think i'll go with your way. If you have any further issues, feel free to drop it here. Thanks :+1:
