### ISSUE TITLE
Error in sw.js registration

### ISSUE THREAD

**Issue by jumasheff** [ooade/NextSimpleStarter#49]
In order to check PWA on dev machine, I built the app and yarn run start. But the project showed an error in console:
Failed to load resource: net::ERR_INVALID_RESPONSE :3000/sw.js

**Comment by AgentChris** [comment]
i have the same problem

A bad HTTP response code (404) was received when fetching the script.
:3000/sw.js Failed to load resource: net::ERR_INVALID_RESPONSE
app.js:7 Error during service worker registration: TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
(anonymous) @ app.js:7
Promise rejected (async)
(anonymous) @ app.js:7
n @ app.js:1
(anonymous) @ app.js:7
n @ app.js:1
window.webpackJsonp @ app.js:1
(anonymous) @ app.js:8

**Comment by ooade** [comment]
Sorry, i created the issue on this [commit](https://github.com/ooade/NextSimpleStarter/commit/8363cdf2e853b416b522d4fed5765503c057b100). I'll fix it ASAP. Thanks :+1:

**Comment by ooade** [comment]
Fixed! :fire:
