### ISSUE TITLE
Lighthouse testing

### ISSUE THREAD

**Issue by luandro** [ooade/NextSimpleStarter#6]
[lighthouse](https://github.com/GoogleChrome/lighthouse) can't perform a test on [https://next-preact.now.sh](https://next-preact.now.sh).

**Comment by ooade** [comment]
It's working fine here:
![lh](https://cloud.githubusercontent.com/assets/11811904/22863620/dc4719d2-f143-11e6-9b36-115a4a4ebe63.png)

And besides, even if it don't work, it would be from lighthouse and not from the web app.

**Comment by luandro** [comment]
Something funny happens here... anyways, thanks. Just curious to see the score. Great project btw!

**Comment by ooade** [comment]
The score is not so cool right now.. I'll make some improvements :smile:

**Comment by luandro** [comment]
Let's get it to 100, I'll see if I can help out :1st_place_medal:

**Comment by ooade** [comment]
@luandro That'll be much appreciated :+1:

**Comment by ooade** [comment]
@luandro we made it to 100 https://pwa-directory.appspot.com/?sort=score&page=2
Thanks to those few changes we made lately, and thanks to you too
