### ISSUE TITLE
How i can add code in the service worker?

### ISSUE THREAD

**Issue by CharlyJazz** [ooade/NextSimpleStarter#62]
I need add code to create push notificacion add background sync, any ideas?

**Comment by ooade** [comment]
Sorry, this took a while but we've switched from using sw-precache to using workbox which will work well for your use case. You can make it happen from this [file](https://github.com/ooade/NextSimpleStarter/blob/master/utils/sw.js). If you have any issues with it, feel free to hit me up here. Thanks!
