### ISSUE TITLE
i can't start this project.

### ISSUE THREAD

**Issue by Rexiduz** [ooade/NextSimpleStarter#66]
<img width="1552" alt="screen shot 2561-07-25 at 17 09 45" src="https://user-images.githubusercontent.com/33196996/43194844-9493f77e-902d-11e8-9135-ebefcff52a1a.png">

i'm student form Thailand. Now, i interesting in PWA with Next.js and research example project. i don't know to fix it. Can you help me please?

**Comment by Rexiduz** [comment]
<img width="1440" alt="screen shot 2561-07-25 at 22 13 29" src="https://user-images.githubusercontent.com/33196996/43209925-0b6f8f82-9058-11e8-933b-833f297f9f21.png">
i'm just use commands "npm install", "npm run dev" and open browser to  "localhost:3000"

**Comment by ooade** [comment]
It shouldn't be that worse, even in development

**Comment by ooade** [comment]
BTW, I noticed there's a slight change to dealing with redux in Next.js which I will update in few minutes. Thanks for notifying me :+1:
