### ISSUE TITLE
Take PWA to 100% again

### ISSUE THREAD

**Issue by ooade** [ooade/NextSimpleStarter#72]
Clone the repo, and use lighthouse(Audits) as a guide. 
Cheers :tada:

**Comment by SanyasiraoM** [comment]
I will do this

**Comment by ooade** [comment]
@SanyasiraoM feel free to tackle any other one asides #74

**Comment by ooade** [comment]
Where we are currently:
![screenshot from 2018-10-03 10-55-06](https://user-images.githubusercontent.com/11811904/46403582-d277f280-c6fa-11e8-9a50-a960f13996d4.png)

Using audits, you'd know what to change and the link attached to each problem will guide you to solving them

**Comment by Developerayo** [comment]
Sill doing this @SanyasiraoM ?

**Comment by Developerayo** [comment]
Ohh it's done :)

**Comment by Developerayo** [comment]
@ooade consider closing this issue? 
Any reason to keep it open?
