### ISSUE TITLE
the live-reload is not working

### ISSUE THREAD

**Issue by serjt12** [ooade/NextSimpleStarter#82]
I followed all the steps to make the app work, but the live-reload doesn't work, in order for the project to work I have to build then run yarn dev, am I mmissing something, thanks in advance.

**Comment by ooade** [comment]
It works. Check this out https://res.cloudinary.com/stackpie/video/upload/v1546972198/2019-01-08_19-12-39_m1b9zn.mp4

**Comment by serjt12** [comment]
that's exactly why I dont get it, as I said I only clone the repo, npm install, npm run  dev and  it says why I explained before...

**Comment by serjt12** [comment]
really really  strange, now I could try it in a mac, worked perfectly... so I don't know, sorry to bother and thank you again.

**Comment by ooade** [comment]
Okay. Glad I was able to help :+1:
