### ISSUE TITLE
ISSUE : Uncaught ReferenceError: webpackHotUpdate is not defined

### ISSUE THREAD

**Issue by talentedandrew** [ooade/NextSimpleStarter#87]
Getting this error (Uncaught ReferenceError: webpackHotUpdate is not defined
) while runnign `npm run dev`

**Comment by ooade** [comment]
It should work fine. Just `npm install`.

Or you can provide some step to reproduce if it doesn't.

Thanks

**Comment by talentedandrew** [comment]
@ooade still getting this error. Below are the steps:
1.cloned this repo
2.installed all dependencies `npm install`
3. ran `npm run dev`


node version : v10.13.0
os : macOS Mojave (version 10.14.3)

**Comment by ooade** [comment]
Hi, can you try deleting your node_modules directory and install again, because I can't seem to reproduce this issue? I'm also running node v10. You could also delete your package lock file before running the install script.

**Comment by talentedandrew** [comment]
@ooade I did a fresh install. Still showing the error on console. Did you try doing a fresh install?

**Comment by ooade** [comment]
Yeah, I did that as well.

**Comment by ooade** [comment]
Here's my fresh install.
![fresh install](https://user-images.githubusercontent.com/11811904/55475106-e8fbf980-560a-11e9-8619-baa013df97cf.png)

**Comment by ooade** [comment]
I've pushed the my lock file tho. I hope it helps :)

**Comment by talentedandrew** [comment]
@ooade Please see the below screenshot
![image](https://user-images.githubusercontent.com/15646138/55476463-422c5300-5634-11e9-9eb0-aae9ed5dcdf8.png)

**Comment by talentedandrew** [comment]
@ooade did you get the issue?

**Comment by ooade** [comment]
Oh! I didn't know it was in the browser's console. It's probably from Next.js. I'll upgrade and see how it goes.

**Comment by ooade** [comment]
@talentedandrew The issue is with workbox conflicting with next.js. I'll try fixing it tomorrow. Thanks for reporting this.

**Comment by ooade** [comment]
Thanks for reporting this @talentedandrew. We are using a more better approach now
