### ISSUE TITLE
Change to using Material Components Web

### ISSUE THREAD

**Issue by ooade** [ooade/NextSimpleStarter#88]
We'll be changing the entire project to using [Material Components Web](https://github.com/material-components/material-components-web). It's currently using Material Design Lite.

Reason for change: 
They don't update mdl again, since they now have mcw.

**Comment by Developerayo** [comment]
Add a description naw 😥

**Comment by 9wisit** [comment]
When?

**Comment by headwinds** [comment]
@ooade do you need any help porting? I know Material very well and would be happy to give back

**Comment by ooade** [comment]
@headwinds Feel free to send in a PR :grinning:

Thanks :)

**Comment by headwinds** [comment]
@ooade great - I'm exploring the repo - I'll make a small draft PR and update 1 component to the latest material UI and we can discuss the results

**Comment by ooade** [comment]
Sure. Good to know 👌

**Comment by headwinds** [comment]
@ooade so when I said I know Material well - I actually know React Material [https://material-ui.com](https://material-ui.com) not Material Components Web - I briefly looked into that project and they look similar but I'd more comfortable with the react version.

So can we go with React Material UI instead? It does seem like it's more suited for NextJS...

**Comment by ooade** [comment]
Cool @headwinds. I love Material UI, as well. The latest releases make a whole lot of sense.
